const inscricaoSucesso = "<img src=\"http://e-doc.pro.br/assets/img/FINALHORIZONTAL.png\" width=\"1200px\" height=\"200px\"></img><h4 style=\"text-align: center;\"><span style=\"color: #00ccff;\"><strong>Bem-Vindo</strong></span></h4> <p>&nbsp;</p> <p><span style=\"color: #000000;\"><strong>Sua inscri&ccedil;&atilde;o foi realizada com sucesso!<br />Acompanhe a gente em nossas redes sociais para ficar por dentro de todas as novidades do IV e-doc.</strong></span></p> <p><span style=\"color: #000000;\"><strong>Ah! E n&atilde;o se esque&ccedil;a, Acesse a plataforma e submeta seus trabalhos.</strong></span></p><p>&nbsp;</p> <p><span style=\"color: #000000;\"><strong><a title=\"Facebook\" href=\"https://www.facebook.com/profile.php?id=100080513694606\" target=\"_blank\" rel=\"noopener\">Facebook</a> | <a title=\"Youtube\" href=\"https://www.youtube.com/channel/UCJuPhHS2bA49pfoQ2NYStPw?hl=pt-br\" target=\"_blank\" rel=\"noopener\">Youtube</a></strong></span></p> <p>&nbsp;</p> <p>&nbsp;</p>";
const pagamentoHomologado = "<h1><strong>IV E-DOC | 2022</strong></h1><p>&nbsp;</p><p>Seu pagamento foi confirmado e sua inscri&ccedil;&atilde;o homologada! Nos acompanhe nas redes sociais para ficar por dentro das novidades</p><p>&nbsp;</p><p><strong><a title=\"\&quot;Facebook\&quot;\" href=\"\&quot;https://www.facebook.com/profile.php?id=100080513694606\&quot;\" target=\"\&quot;_blank\&quot;\" rel=\"\&quot;noopener\&quot;\">Facebook</a> | <a title=\"\&quot;Instagram\&quot;\" href=\"\&quot;https://www.instagram.com/e_docufrrj/?hl=pt-br\&quot;\" target=\"\&quot;_blank\&quot;\" rel=\"\&quot;noopener\&quot;\">Instagram</a></strong></p><p>&nbsp;</p><p>&nbsp;</p>";
const trabalhoSubmetido = "<img src=\"http://e-doc.pro.br/assets/img/FINALHORIZONTAL.png\" width=\"1200px\" height=\"200px\"></img><h4 style=\"text-align: center;\"><span style=\"color: #00ccff;\"><h1><strong>IV E-DOC | 2022</strong>&nbsp;</h1></span></h4> <p>&nbsp;</p> <p><span style=\"color: #000000;\"><strong>Trabalho submetido com sucesso!<br />Acompanhe nossas datas e fique por dentro de tudo que estamos construindo.</strong></span></p> <p><span style=\"color: #000000;\"></span></p><p>&nbsp;</p> <p><span style=\"color: #000000;\"><strong><a title=\"Facebook\" href=\"https://www.facebook.com/profile.php?id=100080513694606\" target=\"_blank\" rel=\"noopener\">Facebook</a> | <a title=\"Youtube\" href=\"https://www.youtube.com/channel/UCJuPhHS2bA49pfoQ2NYStPw?hl=pt-br\" target=\"_blank\" rel=\"noopener\">Youtube</a></strong></span></p> <p>&nbsp;</p> <p>&nbsp;</p>";
const esqueciSenha = "<h1><strong>IV E-DOC | 2022</strong>&nbsp;</h1><p>Para recuperar sua senha siga os passos abaixo:</p><p>1 - Acesse o seguinte endereço <a href=\"http://e-doc.pro.br/reset-senha\">http://e-doc.pro.br/reset-senha</a></p><p>2 - Insira o seguinte código no campo \"Código do email\": #senha#</p><p>3 - Insira sua nova senha no sistema e clique em Enviar</p>";
const documentoValido = "<h1><strong>IV E-DOC | 2022</strong>&nbsp;</h1><p>Nossa equipe avaliou seu comprovante de inscrição e está tudo de acordo.</p><p>Acesse agora mesmo o site http://e-doc.pro.br/ e no menu Ações > Pagamento envie seu comprovante de transferência bancária. </p>";
const pareceristaVinculado = "<h1><strong>IV E-DOC | 2022</strong>&nbsp;</h1><p> Olá! Você foi cadastrado como parecerista do IV E-DOC 2022. Para acessar a área de avaliação de trabalhos você deve acessar a aba “Dashboard” dentro do menu “ações” após logar no sistema com seu e-mail cadastrado e senha. Os trabalhos serão distribuídos para avaliação a partir de fevereiro. </p>";
const trabalhoRecusadoReenviado = "<h1><strong>IV E-DOC | 2022</strong>&nbsp;</h1><p>Seu eixo recebeu um trabalho para nova avaliação através de recurso. Faça login no site, avalie o trabalho ou faça nova distribuição</p>";


module.exports = {
    inscricaoSucesso,
    pagamentoHomologado,
    trabalhoSubmetido,
    esqueciSenha,
    documentoValido,
    pareceristaVinculado,
    trabalhoRecusadoReenviado
};